// Generates the Material 3 colour tokens for the whole app.
//
//   node --import ./scripts/lib/ext-resolve.mjs scripts/m3-theme.mjs
//
// Seed: the brand violet. Scheme: Fidelity (keeps the brand colour exact as the
// primary container; tertiary becomes its warm amber complement). Category
// colours are Material "custom colours": each source hue is harmonized toward
// the seed, then given the standard light-theme role tones
// (color 40 / on-color 100 / container 90 / on-container 10).
import { writeFileSync } from 'node:fs';
import {
  argbFromHex,
  hexFromArgb,
  Hct,
  SchemeFidelity,
  TonalPalette,
  Blend,
  MaterialDynamicColors as D,
} from '@material/material-color-utilities';

const SEED = '#7C3AED';
const scheme = new SchemeFidelity(Hct.fromInt(argbFromHex(SEED)), false, 0);
const role = (r) => hexFromArgb(D[r].getArgb(scheme));
const tone = (palette, t) => hexFromArgb(palette.tone(t));

// Harmonized custom colour → its four light-theme roles.
function custom(hex) {
  const harmonized = Blend.harmonize(argbFromHex(hex), argbFromHex(SEED));
  const p = TonalPalette.fromInt(harmonized);
  return { color: tone(p, 40), on: tone(p, 100), container: tone(p, 90), onContainer: tone(p, 10), soft: tone(p, 95), bright: tone(p, 80) };
}

const CATS = {
  electronics: '#1E88E5', books: '#FBC02D', furniture: '#FB8C00', vehicles: '#43A047', clothing: '#EC407A',
  accessories: '#8E24AA', sports: '#00897B', hostel: '#00ACC1', academic: '#3949AB', other: '#8D6E63',
};
// Accent families the existing UI already uses (stickers, toasts, chips).
const ACCENTS = { sun: '#FFC107', bubblegum: '#EC407A', mint: '#2EB872', sky: '#29A9F5', tangerine: '#FF7A1A' };

const lines = [];
const add = (k, v) => lines.push(`  --color-${k}: ${v};`);

// Material 3 roles
for (const r of ['primary', 'onPrimary', 'primaryContainer', 'onPrimaryContainer', 'secondary', 'onSecondary', 'secondaryContainer', 'onSecondaryContainer', 'tertiary', 'onTertiary', 'tertiaryContainer', 'onTertiaryContainer', 'error', 'onError', 'errorContainer', 'onErrorContainer', 'surface', 'surfaceDim', 'surfaceBright', 'surfaceContainerLowest', 'surfaceContainerLow', 'surfaceContainer', 'surfaceContainerHigh', 'surfaceContainerHighest', 'onSurface', 'onSurfaceVariant', 'outline', 'outlineVariant', 'inverseSurface', 'inverseOnSurface', 'inversePrimary']) {
  add('m3-' + r.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase()), role(r));
}

// Existing app tokens, re-pointed at Material tones so every screen follows.
const P = scheme.primaryPalette;
const NV = scheme.neutralVariantPalette;
[[50, 95], [100, 90], [200, 80], [300, 70], [400, 60], [500, 50], [600, 40], [700, 30], [800, 20]].forEach(([k, t]) => add(`brand-${k}`, tone(P, t)));
add('ink', role('onSurface'));
add('cream', role('surface'));
// Tinted neutrals instead of flat slate greys (secondary text, hairlines).
[[50, 98], [100, 95], [200, 90], [300, 80], [400, 60], [500, 50], [600, 40], [700, 30], [800, 20]].forEach(([k, t]) => add(`slate-${k}`, tone(NV, t)));
for (const [name, hex] of Object.entries(ACCENTS)) {
  const c = custom(hex);
  add(name, c.bright);
  add(`${name}-soft`, c.container);
}
for (const [name, hex] of Object.entries(CATS)) {
  const c = custom(hex);
  add(`cat-${name}`, c.color);
  add(`cat-${name}-container`, c.container);
  add(`on-cat-${name}-container`, c.onContainer);
  add(`cat-${name}-bright`, c.bright);
}

const css = `/* GENERATED by scripts/m3-theme.mjs from seed ${SEED} (Material 3, Fidelity scheme).
   Do not edit by hand: change the seed or source hues and re-run the script. */
@theme static {
${lines.join('\n')}
}
`;
writeFileSync(new URL('../src/m3-tokens.css', import.meta.url), css);
console.log(css);
